name: Deploy to ECR Repository
run-name: >
  ${{ github.sha }} - "${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}"
on:
  push:
    branches:
      - development
      - production
      - 'release*'

jobs:
  notify-slack-on-push:
    if: >
      (github.ref == 'refs/heads/production' ||
       github.ref == 'refs/heads/development' ||
       startsWith(github.ref, 'refs/heads/release')) &&
      !startsWith(github.event.head_commit.message, 'Merge pull request')
    name: Alert on Direct Push To Main Branches
    uses: ./.github/workflows/notify-slack-on-push.yaml
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      commit: ${{ github.sha }}
      actor: ${{ github.actor }}
      event_name: ${{ github.event_name }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      before: ${{ github.event.before }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      