name: Deploy to ECR Repository
on:
  push:
    branches:
      - development
      - Development
      - production
      - 'release*'
    paths-ignore:
      - '**/README.md'
      - 'docs'
      - '.dockerignore'
      - '.gitignore'
      - 'Makefile'

jobs:
  notify-slack-on-push:
    if: "! startsWith(github.event.head_commit.message, 'Merge pull request')"
    name: Alert on Direct Push To Main Branches
    uses: ./.github/workflows/alert-on-push.yaml
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      commit: ${{ github.sha }}
      actor: ${{ github.actor }}
      event_name: ${{ github.event_name }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      before: ${{ github.event.before }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
