name: Test Pull Request
on:   
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'
      - 'templates'
      - 'utils/docker'
      - 'utils/scripts'

jobs:
  application_code_test:
    name: Application Code Test
    uses: ./.github/workflows/application_code_test.yaml
  test_image_deployment: 
    name: Test Image Deployment
    needs: application_code_test
    uses: ./.github/workflows/test_image_deployment.yaml
    