name: Notify Slack
on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
        description: 'Status of the workflow (success or failure)'
      repository:
        required: true
        type: string
        description: 'GitHub repository name'
      branch:
        required: true
        type: string
        description: 'GitHub branch name'
      commit:
        required: true
        type: string
        description: 'GitHub commit SHA'
      actor:
        required: true
        type: string
        description: 'GitHub actor (user who triggered the workflow)'
      workflow:
        required: true
        type: string
        description: 'GitHub workflow name'
      run_id:
        required: true
        type: string
        description: 'GitHub workflow run ID'
      logs:
        required: false
        type: string
        description: 'Failed job logs (only for failure status)'
      color:
        required: true
        type: string
        description: 'Color for the Slack message (e.g., #36a64f for success, #ff0000 for failure)'
      message:
        required: true
        type: string
        description: 'Message for the Slack notification'
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:

      # - name: Debug Inputs
      #   run: |
      #     echo "Status: ${{ inputs.status }}"
      #     echo "Repository: ${{ inputs.repository }}"
      #     echo "Branch: ${{ inputs.branch }}"
      #     echo "Commit: ${{ inputs.commit }}"
      #     echo "Actor: ${{ inputs.actor }}"
      #     echo "Workflow: ${{ inputs.workflow }}"
      #     echo "Run ID: ${{ inputs.run_id }}"
      #     echo "Logs: ${{ inputs.logs }}"
      #     echo "Color: ${{ inputs.color }}"
      #     echo "Message: ${{ inputs.message }}"

      - name: Notify Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "username": "GitHub Actions Bot",
              "icon_emoji": ":github:",
              "attachments": [
                {
                  "color": "${{ inputs.color }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.message }}"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Repository:*\n<https://github.com/${{ inputs.repository }}|${{ inputs.repository }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Branch:*\n<https://github.com/${{ inputs.repository }}/tree/${{ inputs.branch }}|`${{ inputs.branch }}`>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit:*\n<https://github.com/${{ inputs.repository }}/commit/${{ inputs.commit }}|`${{ inputs.commit }}`>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Author:*\n${{ inputs.actor }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow:*\n`${{ inputs.workflow }}`"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Build Logs:*\n<https://github.com/${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}|View Logs>"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Failed Jobs:*\n${{ inputs.logs || 'No failed jobs' }}"
                      }
                    }
                  ]
                }
              ]
            }